### ISSUE TITLE
ToolTip display issue

### ISSUE THREAD

**Issue by littlegolden** [clarkwinkelmann/flarum-ext-who-read#5]
The over-flow configuration need to be changed.
![image.png](https://i.loli.net/2020/03/10/lIScAOmizG4w9Cx.png)

**Comment by clarkwinkelmann** [comment]
Yes I noticed that. I'm a bit reluctant to change the Flarum overflow styles for the modal as I'm not sure what could break.

**Comment by littlegolden** [comment]
Can it be this? The ToolTip box move to right when it touches the edge of the outer box?
![image.png](https://i.loli.net/2020/03/11/WLsEGbZrVDxnFug.png)

**Comment by clarkwinkelmann** [comment]
Ideally yes the tooltip should align based on the bounding box of the modal.

I'll see whether that's doable in a next release.

**Comment by clarkwinkelmann** [comment]
Fixed in version 1.2.1
